version: "3.1"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017

  api:
    image: fastapi
    container_name: api
    restart: always
    ports:
      - 8000:8000
    depends_on:
      - mongo
